server:
  port: ${PORT:8080}

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 30000
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Creates/Updates tables automatically
    show-sql: true      # Logs SQL statements
    open-in-view: false  # This allows lazy loading during view rendering but can lead to N+1 query issues.



# Optional: Enable logging for easier debugging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
